name: Super-Linter
on:
  push:
  pull_request:
    branches:
      - main
      - master

jobs:
  super-linter:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Super-Linter
        uses: github/super-linter@v3
        with:
          lint-languages: yaml
